### ISSUE TITLE
Wait until Untitled is named before adding to daily list

### ISSUE THREAD

**Issue by bravebellows** [franciskafieh/obsidian-list-modified#35]
The plugin is working as intended, however I have go to back to the daily list and remove the [[Untitled]] links. I believe the file was added to the daily note before I finished renaming the file.

Keep up the good work!

**Comment by franciskafieh** [comment]
Obsidian should automatically rename the link when you rename the file. If the file is no longer called Untitled, the link should automatically change (no need to remove it)

Also related to #30 

Please add your feedback there if renaming is not a sufficient solution.

P.S. I would highly recommend using quick switcher instead of new file. This way, the file is created with the name you want, and you can make sure a file does not already exist for the desired subject.

![image](https://user-images.githubusercontent.com/93789670/166009324-38dcc95a-d01a-4c5c-927b-5ca7575933ec.png)

**Comment by bravebellows** [comment]
Thank you. It's a good workaround and a good practice to have

—Andy
