### ISSUE TITLE
Option to have no heading or use a "body text" for heading

### ISSUE THREAD

**Issue by sotakal** [franciskafieh/obsidian-list-modified#54]
I've had my output format set to
`- Edited [[link]]`
and I've liked this minimalist format. The new version of the plugin forces me to use a heading, and this is cumbersome. I rarely use headings in my notes because I find them huge and don't want to tinker with themes, CSS or styling.

If headings really are mandatory, I'd prefer to only a heading formatted as bold body text that says **Modified today:**, without being forced to use an actual h1/h2/etc. heading. Unfortunately when I tried to specify my heading as
`**Modified today:**`
the plugin ignored my setting.

**Comment by franciskafieh** [comment]
The reason I force the user to use headings is because they are easily cached by obsidian. I may add the option to choose something else once i figure out how caching "blocks" (as obsidian calls them) works. There are a few more features I have to finish before releasing 2.1, so I'll have to put this on the backburner.

As a temporary workaround, you can try copying and pasting an invisible character (https://www.editpad.org/tool/invisible-character) into the settings. Make a small heading (h3, h4, whatever level you want) with just the invisible character as the name. This **should** appear invisible in reading/live preview mode. Give it a try and let me know :)

**Comment by franciskafieh** [comment]
Just wanted to mention that (because this feature requires a lot of change to implement) anyone else who would like it should heart the original post. I just want to see how urgent and necessary of a feature this would be.

Currently back to working on the 2.1 rewrite, and the easiest solution for now is to have a "primary" / h1 header that can have content replaced under it.

**N.B. an empty header (a space character) should still work, as it would simply appear as an empty line in the file (under live preview mode)**

**Comment by franciskafieh** [comment]
Although making the primary heading option would be hard, making the modified h3 optional would be easy ^^

**Comment by jfgrtsn** [comment]
> Now the plugin does not create the "modified" heading unless the separate created or deleted options are toggled on. Now there is no heading redundancy in this manner

This worked great for me—thanks!

**Comment by franciskafieh** [comment]
Feel free to look at #90

**Comment by franciskafieh** [comment]
Fixed in 3.0! Please see https://github.com/franciskafieh/obsidian-list-modified/releases/tag/3.0.0-alpha for release info and alpha installation instructions.
