### ISSUE TITLE
[FR] Allow periodic notes other than daily (i.e. weekly, monthly, quarterly, yearly)

### ISSUE THREAD

**Issue by brimwats** [franciskafieh/obsidian-list-modified#56]
## First Steps
- [x] I've ensured that this feature request **does not already exist** by [using the search issues feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
- [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
- [x] I'm on the latest release of obsidian-list-modified

## Describe the desired feature
Please provide a clear description of the feature.

- I'd like to have list modified post at the end of my weekly note instead of my daily one, as I'm switching to using weekly note.
format could be like:

Created date: yyyy-mm-dd
- note x
- y
- z

## Possible alternatives
What are some possible alternatives? Have you tried any of them?

just maintaining daily notes for this plugin alone?

**Comment by franciskafieh** [comment]
Are the weekly notes created with periodic notes? ---- On Fri, 11 Nov 2022 18:32:43 -0500  ***@***.***  wrote ----
First Steps

 I've ensured that this feature request does not already exist by using the search issues feature
 I've read the documentation (see the README)
 I'm on the latest release of obsidian-list-modified

Describe the desired feature
Please provide a clear description of the feature.

I'd like to have list modified post at the end of my weekly note instead of my daily one, as I'm switching to using weekly note.
format could be like:

Created date: yyyy-mm-dd

note x
y
z

Possible alternatives
What are some possible alternatives? Have you tried any of them?
just maintaining daily notes for this plugin alone?
Additional info?

**Comment by franciskafieh** [comment]
> The settings are set up so they can be, but I usually create them by hand. Either way, same folder. So periodic note settings:

Yes, that should be all that matters. This means I'd be able to pull the name of the file from those settings instead of the user needing to enter it. Thing is, I was also thinking of going back to the v1 of allowing users to make custom log files. Will probably implement these at the same time eventually.

**Comment by franciskafieh** [comment]
Actually wondering how custom file select would work. Maybe I'll make a "log" option where one constant file is selected and there is a new heading every day? Going to open another issue for that, since it's unrelated to your FR

**Comment by brimwats** [comment]
Thank you for thinking about it!

**Comment by franciskafieh** [comment]
going to prioritize this as it should be super simple to implement

**Comment by franciskafieh** [comment]
I do plan on getting this added for release 2.1, but as per the README:

> development of this plugin is on hold until February as I am very busy with academics. This plugin is not abandoned.

I hope to get this released ASAP, but I have a really tight schedule ATM and do not have time to devote to the plugin until february.

**Comment by brimwats** [comment]
there's no stress @franciskafieh !

**Comment by franciskafieh** [comment]
just wondering @rmchale @brimwats , would allowing only daily/weekly/monthly/... at a time suffice? or would you prefer having multiple on at once?

**Comment by franciskafieh** [comment]
> I feel like a regex for file selection could work..

if you mean to select the current periodic note, there's a library that the periodic notes plugin author wrote that does this, so we wouldn't need a regex

**Comment by brimwats** [comment]
> just wondering @rmchale @brimwats , would allowing only (one of) daily/weekly/monthly/... at a time suffice? or would you prefer having multiple on at once?

I generally have a monthly one and it would be nice to open it in upcoming but not necessary!

**Comment by franciskafieh** [comment]
> upcoming

Would you mind explaining to me what upcoming is? I've never used periodic notes, but I'm looking through it right now, and I can't find any feature with this name

**Comment by franciskafieh** [comment]
Implemented a dropdown menu to choose from daily/weekly/monthly in 2.1. Currently, quarterly and yearly are not options because I couldn't see why people would want them, and I'd imagine they would get slow pretty quick, as more files add up to the list.

**Comment by brimwats** [comment]
thank you so much!!

**Comment by franciskafieh** [comment]
Hey everyone, just released [version 2.1](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/2.1). Feel free to give it a spin and let me know how it goes!
