### ISSUE TITLE
[FR] Option for blank line between header and list of touched notes

### ISSUE THREAD

**Issue by jfgrtsn** [franciskafieh/obsidian-list-modified#63]
## First Steps

-   [x] I've ensured that this feature request **does not already exist** by [using the search issues feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [x] I'm on the latest release of obsidian-list-modified

## Describe the desired feature

I prefer to include a blank line after headings in my notes, but this plugin strips out the blank line between the designated header and the list of created/updated notes, even if I manually put it back. I would love an option to include the blank line after the heading.

## Possible alternatives

The workaround is to wait until the next day and then manually add the blank like after the header.

**Comment by franciskafieh** [comment]
I could add this. I'll probably just have an option to add a newline character in the header text field

**Comment by jfgrtsn** [comment]
Works for me

**Comment by franciskafieh** [comment]
Sorry for the long time since the last update! Just added this and it will be released in 2.1 (coming within the next week). I implemented it the way you originally wanted, with a setting that does this for **every** heading created by OLM. This is because most people who do add a blank line after a heading do it for all their headings (to follow a sort of style standard.)

**Comment by franciskafieh** [comment]
released: [version 2.1](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/2.1)
