### ISSUE TITLE
Cannot find my daily notes

### ISSUE THREAD

**Issue by ScottKillen** [franciskafieh/obsidian-list-modified#7]
The date format in my daily notes settings is 'YYYY/MM-MMMM/YYYY-MM-DD'

This causes the plugin to warn that no daily file with this name exists.

**Comment by franciskafieh** [comment]
@ScottKillen could you try using using 'YYYY[/]MM-MMMM[/]YYYY-MM-DD'? ofc remove the quotes...

as in the following:
![image](https://user-images.githubusercontent.com/93789670/161391821-6c8fa50d-b323-43ef-a573-b059e10f217d.png)

I need to update the description of that setting. It should say to put anything that is not a date format into square brackets.

LMK if that works! Thanks for reporting!

**Comment by franciskafieh** [comment]
[I pushed a description change that should make it a little more clear.](https://github.com/franciskafieh/obsidian-list-modified/commit/5f7f245db28372519c8340d875c2205b652ab10e).. might change this setting in the future, but it's an easy fix, so not a big priority

**Comment by ScottKillen** [comment]
Thank for looking at this.

So I used 'YYYY[/]MM-MMMM[/]YYYY-MM-DD' instead and got the same error.

Would it be possible to read the Daily Note setting?

**Comment by franciskafieh** [comment]
> Thank for looking at this.
> 
> So I used 'YYYY[/]MM-MMMM[/]YYYY-MM-DD' instead and got the same error.
> 
> Would it be possible to read the Daily Note setting?

I'm very busy atm, but I'll try to look into this tmr if I have time

**Comment by franciskafieh** [comment]
Hey @ScottKillen!

I am taking a quick glance before I go to sleep. In a new vault, having `YYYY/MM-MMMM/YYYY-MM-DD` in the 'Daily Note Format' field actually does locate files using the following format:

![image](https://user-images.githubusercontent.com/93789670/161410526-abadc041-9810-4ecd-b644-f9734c42ea78.png)

For me (on latest build), the problem is rather
![image](https://user-images.githubusercontent.com/93789670/161410530-e715c5b7-928c-4344-bc9f-fce706708fe4.png)

Will have to take a look tmr. probably an easy fix

**Comment by franciskafieh** [comment]
Edit: found a fix! Just need to return if `cache === undefined || cache.links === undefined`... god I hate javascript

other than that, it seems to be working for me

**Comment by franciskafieh** [comment]
Really sorry for comment spam, but I released a new version 0.0.2. Please try downloading it and see if it fixes your issue!

On this version, I cannot reprod. the bug you have reported

here is the result:
![image](https://user-images.githubusercontent.com/93789670/161410677-194ffe8a-bc7b-49ab-83a0-5b718b6cf75d.png)


with these settings:
![image](https://user-images.githubusercontent.com/93789670/161410686-acafd5a8-a6bc-4a3a-85d0-5e587c4ec18a.png)
`YYYY/MM-MMMM/YYYY-MM-DD`

and

![image](https://user-images.githubusercontent.com/93789670/161410699-bb8ced59-18cb-4c90-8e77-9ab24245f7ad.png)
exact same format, `YYYY/MM-MMMM/YYYY-MM-DD`


let me know if this fixes it. otherwise, could you provide `[vault file path]/.obsidian/plugins/obsidian-list-modified/data.json` and `[vault file path]/.obsidian/daily-notes.json` please?

thanks so much!

**Comment by ScottKillen** [comment]
That worked.

Thanks!

**Comment by ScottKillen** [comment]
Forgot to say. I love this plugin!
